name: Quick Submit

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  run-scenario:
    if: startsWith(github.head_ref, 'quick-submit-')
    uses: RDI-Foundation/agentbeats-leaderboard-template/.github/workflows/run-scenario.yml@staverm/amber-runner
    permissions:
      id-token: write
      contents: write
